<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_Wp
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 * @var $this Popov_Wp_Block_Last
 */
?>
<div class="recent-posts">
<?php if ($posts = $this->getPosts()): ?>
    <div class="owl-carousel">
        <?php foreach ($posts as $post): ?>
            <div class="item">
                <?php $postDate = Mage::helper('core')->formatDate($post->getCreatedTime(), 'long', false) ?>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="post-image">
                            <?php if ($post->getImage()) : ?>
                                <a href="<?php echo $post->getPostUrl(); ?>">
                                    <?php /*<img src="<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($post, 'image');?>" alt="<?php echo $this->escapeHtml($post->getPostTitle());?>" />*/?>
                                    <img src="<?php echo $post->getImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle());?>" />
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="post-date">
                            <span class="day"><?php echo $post->getDay(); ?></span>
                            <span class="month"><?php echo $post->getMonthShort(); ?></span>
                        </div>
                        <div class="postTitle">
                            <h2><a href="<?php echo $post->getPostUrl(); ?>" ><?php echo $post->getPostTitle(); ?></a></h2>
                        </div>
                        <div class="postContent"><?php echo $post->getPostExcerpt(); ?></div>
                        <a class="readmore" href="<?php echo $post->getPostUrl(); ?>"><?php echo $this->__("Read more >");?></a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
</div>